### PR TITLE
Remove XHR from pending JS on exception

### LINKED ISSUE #49: Attempting to run a test against a site at 127.0.0.1 hangs at the login screen
When running a behat test against a site with `$CFG->behat_wwwroot` set to 127.0.0.1, the test hangs at the "I enter the app" step, and eventually times out.

The cause appears to be that the app sends an XHR to www.127.0.0.1, which throws an "Invalid URL" exception. This leaves the XHR on the pending_js list, so the behat test never thinks the step is complete.

### PR DESCRIPTION
**Pull request by marxjohnson**
This should resolve #49.

### CODE REVIEW

File: tests/behat/app_behat_runtime.js [hunk 1]
```diff
@@ -98,15 +98,20 @@
...
+            // Detect when it finishes and remove it from the list.
+            this.addEventListener('loadend', function() {
+                removePending(key);
+            });
 
-        return realOpen.apply(this, arguments);
+            return realOpen.apply(this, arguments);
+        } catch (e) {
+            removePending(key);
+            return false;
```
Comment (NoelDeMartin) [inline tests/behat/app_behat_runtime.js:113]: In order to keep the default behavior in case of an error, could we throw the error again after removing the pending request instead of returning false? I think it should also solve the issue you mentioned.

**Review by NoelDeMartin — CHANGES_REQUESTED** [review]
Hey thanks for opening the issue and providing a fix. I only have one comment about your solution, when that is resolved we can go ahead and merge this.

**Comment by marxjohnson** [comment]
@NoelDeMartin Good point, I've updated the branch with that change, and confirmed that it works.

**Review by NoelDeMartin — APPROVED** [review]
